### PR TITLE
Improvements made during Amel_HAv3.1 reruns. 

### PR DESCRIPTION
**Pull request by littleblackfish**

### CODE REVIEW

**Review by vpbrendel — COMMENTED** [review]
If you don't want BWASPR, I don't think you need cpanm, or do you?

**Comment by littleblackfish** [comment]
No, unfortunately we have 2 more ancient perl scripts remaining in BWASP, one of them require the infamous Math::Pari. 
If I had my way I'd port those to python3, along with the few remaining python2 scripts to futureproof BWASP, but I think we can simply version this 1.0 and freeze in singularity hub; that works too.

**Comment by littleblackfish** [comment]
I tested this final version of the container with 2 se experiments. Once we tag it 1.0 I will re-run everything in carbonate using the included Apis_mellifera.sh script, and then we can freeze. You were right that FastQC, Cutadapt and Trim Galore were very outdated. Even Bowtie had a version bump. As far as I can see everything is up to date now. Good time to freeze container just before write up.

**Comment by vpbrendel** [comment]
For Singularity.v1.0:

-line 6: write "from the Brendel Group" (add "the")
- line 44: should we update our Bismark fork?
-line 54 paragraph: I think we don't need Aspera given the current sratools download commands
-line 61: please insert space before the closing ' (allows to use open the link in vi ...)

**Comment by vpbrendel** [comment]
I still don't understand the revised Singularity recipe. You dropped installation of the prerequisites for genometools and AEGeAn, and in consequence, neither of these tools install.
Is your intent to remove the parse_gff3 step (which requires AEGeA, which requires genometools, ...) and move that to a BWASPR recipe?

**Pull request merged**
