### PR TITLE
Updates to documentation and

### PR DESCRIPTION
**Pull request by vpbrendel**
xgetSRAacc.

1) Download via fasterq-dump is now run by the script xgetSRAacc, called by the Makefiles. An important addition is that if a sample has multiple runs under different SRA accessions, then the accession numbers can be combined by _, e.g. SRRnbr1_SRRnbr2. xgetSRAacc will then download both SRRnbr1 and SRRnbr2 and produce a combined read file SRRnbr1_SRRnbr2 for analysis, which represents the actual biological sample.

2) NCBI SRA Toolkit now requires user configuration, at least once on each machine you want to run fasterq-dump, for example. Even when running BWASP with singularity, you must do this once before using an HPC machine. This step is documented in HOWTO.md.

### CODE REVIEW

**Comment by Clairemorandin** [comment]
I am not sure I shall write this error but I found a few minor typo in the doc
simultaneosly
defaul

Otherwise well explained, easy to do, I could understand and it is running so I guess that's already a good sign :) 

Perhaps good to add a few lines for people who don't have their data on NCBI yet, I mean 95% of new studies won't release their dataset before publications. Just perhaps add where raw/cleaned data should be added manually if not available yet.

**Comment by vpbrendel** [comment]
Thanks, Claire.
1) typos fixed
2) a paragraph on getting the data added
3) a link put into HOWTO to the data/README

Ready for a next round of scrutiny and Kate's testing.

**Comment by katemortensen** [comment]
I was able to get the xgetSRAacc to work with xdoit and just with xgetSRAacc alone on Carbonate.

**Review by katemortensen — APPROVED** [review]
Looks good!

**Pull request merged**
